import stat
from pathlib import Path

from captain_hook.models import Hook


def write_hook(hook: Hook, virtual_env: Path) -> None:
    hook_path = Path(".git/hooks") / hook.hook_type.value

    file_content = (
        "#!/bin/bash\n"
        "# This file was automatically generated by captain-hook\n"
        f"source {virtual_env}/bin/activate\n"
    )

    for command in hook.commands:
        file_content += f"{command.command}\n"

    hook_path.write_text(file_content)

    hook_path.chmod(hook_path.stat().st_mode | stat.S_IEXEC)
